services:
  sheep:
    image: sheep:latest   # or build: .
    container_name: sheep
    environment:
      VERBOSE: "true"
      WATCHLIST_PATH: /data
      KAFKA_PRODUCER_BOOTSTRAP_SERVERS: broker:29092
      KAFKA_OUTPUT_TOPIC: actions
    volumes:
      - ./data:/data
    networks:
      - shepherd_net

networks:
  shepherd_net:
    external: true
