path:
  sheep_cache: "sheep_shear/config/sheep_cache.json"

sec:
  user_agent: "casper casper@2apollo.com"
  timeout: 30
  max_retries: 5
  backoff_base: 2.0

kafka:
  kafka_properties_path: "sheep_shear/kafka/kafka.properties"
  action_topic: "action_topic"
  heartbeat_topic: "heartbeat_topic"
  sleep_time: 10
  heart_beat_freq: 20
  queue_maxsize: 100_000